// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp9jSDApldrMH3CbSYDwJ7WtfDXfnxV0',
    appId: '1:593877303281:web:13e9e30ed388fb9a0b0e50',
    messagingSenderId: '593877303281',
    projectId: 'ador-poc',
    authDomain: 'ador-poc.firebaseapp.com',
    storageBucket: 'ador-poc.firebasestorage.app',
    measurementId: 'G-3BC4Y7XFRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbdckcb8q9Y3BFS3WOtpviC5-YtT2W9xE',
    appId: '1:593877303281:android:f1c976a9bb890b9f0b0e50',
    messagingSenderId: '593877303281',
    projectId: 'ador-poc',
    storageBucket: 'ador-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdOjO1sjhHNH61vb-SnAxRDcizW0_rAjY',
    appId: '1:593877303281:ios:a2779152f2aa816a0b0e50',
    messagingSenderId: '593877303281',
    projectId: 'ador-poc',
    storageBucket: 'ador-poc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOfflineCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdOjO1sjhHNH61vb-SnAxRDcizW0_rAjY',
    appId: '1:593877303281:ios:a2779152f2aa816a0b0e50',
    messagingSenderId: '593877303281',
    projectId: 'ador-poc',
    storageBucket: 'ador-poc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOfflineCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRp9jSDApldrMH3CbSYDwJ7WtfDXfnxV0',
    appId: '1:593877303281:web:9df167469ad4d1110b0e50',
    messagingSenderId: '593877303281',
    projectId: 'ador-poc',
    authDomain: 'ador-poc.firebaseapp.com',
    storageBucket: 'ador-poc.firebasestorage.app',
    measurementId: 'G-LYPFHCB0YG',
  );
}
